=== medharik/ifiaglicence2019/xml_projet_2019/film.dtd
<!ELEMENT cdtheque (cd*) >
<!ATTLIST cdtheque date CDATA #REQUIRED>
<!ATTLIST cdtheque auteur CDATA #REQUIRED>
<!ELEMENT cd	(titre,artiste+,style?)>
<!ELEMENT titre	(#PCDATA)>
<!ELEMENT style	(#PCDATA) >
<!ELEMENT artiste	(#PCDATA)>
<!ATTLIST style nom CDATA #REQUIRED>

=== medharik/ifiaglicence2019/xml_projet_2019/film.xml
<!-- prologue  -->
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- dtd externe system -->

<!DOCTYPE cdtheque SYSTEM "./film.dtd">

<cdtheque date="01-01-2019" auteur="omar">
    <cd>
        <titre>les irreprochables </titre>
        <artiste>omar sy </artiste>
        <artiste>omar my </artiste>
        <style nom="DRAMA" />
    </cd>

    <cd>
        <titre>les miserables </titre>
        <artiste>robert de niro</artiste>
    </cd>
</cdtheque>
